name: .Net 6 CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore CustomerManagement.sln

    - name: Build
      run: dotnet build CustomerManagement.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test CustomerManagement.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
