name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./tests/CustomerManagement.Integration.Tests
      run: dotnet restore
    - name: Build
      working-directory: ./tests/CustomerManagement.Integration.Tests
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./tests/CustomerManagement.Integration.Tests
      run: dotnet test --collect:"XPlat Code Coverage"
    - name: TestCodeCov
      working-directory: ./tests/CustomerManagement.Integration.Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/ /p:ExcludeByAttribute="IntegrationTests" /p:ExcludeByFile=\"**/Repositories/*.cs,**/BusinessEntities/ImplementationWorkOfClasses.cs\"
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        #working-directory: ./tests/CustomerManagement.Integration.Tests
        files: ./tests/CustomerManagement.Integration.Tests/TestResults/coverage.opencover.xml
        flags: unittests 
        name: codecov-umbrella
        fail_ci_if_error: true 
        verbose: true
